### ISSUE TITLE
Filtering table field support ?

### ISSUE THREAD

**Issue by Heu** [siddontang/go-mysql-elasticsearch#26]
This is missing feature as a note in README, but after take a look in code I've found that it is a trivial change as : 
sync.go:197
```Go
func (r *River) makeInsertReqData(...) {
...
    if name != "-" {
	req.Data[name] = r.makeReqColumnData(&c, values[i])
    } 
...
```
and similar for makeUpdateReqData

By this way I can filter table field in rule's field config as: 
```toml
[[rule]]

    [rule.field]
    password = "-"

````

So my question is: Does it has any risk?
