### ISSUE TITLE
请问可不可以配置mysql 和 es 对应的字段不一样

### ISSUE THREAD

**Issue by Jetereting** [siddontang/go-mysql-elasticsearch#279]
比方说 table1 有个 name字段；我想对应 es的 UName

**Comment by siddontang** [comment]
https://github.com/siddontang/go-mysql-elasticsearch#rule-field-types

**Comment by Jetereting** [comment]
```toml
# MySQL data source
[[source]]
schema = "qdxg"


tables = ["role"]

[[rule]]
schema = "qdxg"
table = "role"
index = "autest"
type = "t_role"

filter = ["Status","RoleName"]

    [rule.field]
    title="URoleName"
```

I try this, but not work.

**Comment by Jetereting** [comment]
```toml
filter = ["Status","RoleName"]

    [rule.RoleName]
    title="URoleName"
```

not work also.

**Comment by Jetereting** [comment]
```toml
filter = ["Status","RoleName"]

    [rule.field]
    RoleName="URoleName"
```

not work, and RoleName gone.
