### ISSUE TITLE
one-to-many join question

### ISSUE THREAD

**Issue by vcostin** [siddontang/go-mysql-elasticsearch#48]
Hi,
I played with this library I've managed to import data to Elastic very cool thanks, but I didn't manage to store nested indexes. I want to consult maybe someone cold point on what I'm doing wrong.
So here I have two cases in ```./etc/river.toml``` file:

1. when relation is in the same schema
2. when relation is in different schema and it's related to first schema

```toml
# MySQL data source
[[source]]
schema = "blog"
tables = ["users", "posts"]

# MySQL data source
[[source]]
schema = "gallery"
tables = ["user_gallery", "images"]

[[rule]]
schema = "blog"
table = "users"
index = "users"
type = "user"

[[rule]]
schema = "blog"
table = "posts"
index = "posts"
type = "post"
parent = "user_id"

[[rule]]
schema = "gallery"
table = "user_gallery"
index = "galleries"
type = "gallery"
parent = "user_id"

[[rule]]
schema = "gallery"
table = "images"
index = "images"
type = "image"
parent = "user_gallery_id"
```
So with this I've manage to store users but it didn't create nested dependencies and it didn't store other type of index it only created them.

###### offtop
I configured a Data Importer Handler for solr and there I specifically described what field is related to other from what data source. So maybe I've missed something.
